os: windows
language: shell
script:
  - choco install nuget.commandline
  - choco install visualstudio2017community --package-parameters "--add Microsoft.VisualStudio.Workload.ManagedDesktop"
  - powershell "cmd /C travis-build.bat"
