trigger:
- master

jobs:
- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - bash: |
      set -e
      curl -sLo pahkat.exe https://github.com/divvun/pahkat/releases/download/0.6.0/pahkat.exe
      git clone https://github.com/divvun/divvun-ci-config.git
      openssl aes-256-cbc -d -in ./divvun-ci-config/config.txz.enc -pass pass:$DIVVUN_KEY -out config.txz -md md5
      7z e config.txz
      tar xf config.tar
    displayName: 'Install prerequisites'
    env:
      DIVVUN_KEY: $(divvunKey)
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'divvun-installer'
      pipeline: 'divvun.pahkat-client-core'
      buildVersionToDownload: 'latestFromBranch'
      allowPartiallySucceededBuilds: false
      branchName: 'refs/heads/master'
      artifactName: 'windows'
      downloadPath: '$(System.DefaultWorkingDirectory)' 
    displayName: 'Download pahkat-client-core artifact'
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: 'Pahkat.sln'
    displayName: 'Restore NuGet packages'
  - task: VSBuild@1
    inputs:
      solution: Pahkat.sln
      platform: x86
      configuration: release
    displayName: 'Build'
  - script: |
      # todo: remove when download artifact works
      dir
      set PATH="%PATH%;C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool;$(System.DefaultWorkingDirectory)"
      "C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool\signtool" sign /t http://timestamp.verisign.com/scripts/timstamp.dll /f "$(System.DefaultWorkingDirectory)\enc\creds\windows\divvun.pfx" /p %PFX_PASSWORD% /d "Divvun Updater" .\Pahkat\bin\x86\Release\updater.exe
      "C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool\signtool" sign /t http://timestamp.verisign.com/scripts/timstamp.dll /f "$(System.DefaultWorkingDirectory)\enc\creds\windows\divvun.pfx" /p %PFX_PASSWORD% /d "Divvun Installer" .\Pahkat\bin\x86\Release\Pahkat.Sdk.dll
      "C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool\signtool" sign /t http://timestamp.verisign.com/scripts/timstamp.dll /f "$(System.DefaultWorkingDirectory)\enc\creds\windows\divvun.pfx" /p %PFX_PASSWORD% /d "Divvun Installer" .\Pahkat\bin\x86\Release\pahkat_client.dll
      "C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool\signtool" sign /t http://timestamp.verisign.com/scripts/timstamp.dll /f "$(System.DefaultWorkingDirectory)\enc\creds\windows\divvun.pfx" /p %PFX_PASSWORD% /d "Divvun Installer" .\Pahkat\bin\x86\Release\DivvunInstaller.exe
      "C:\Program Files (x86)\Inno Setup 5\ISCC.exe" /Qp /O.\output /S"signtool=C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool\signtool.exe sign /t http://timestamp.verisign.com/scripts/timstamp.dll /f "$(System.DefaultWorkingDirectory)\enc\creds\windows\divvun.pfx" /p %PFX_PASSWORD% $f" setup.iss
      copy output\install.exe "$(System.DefaultWorkingDirectory)\divvun-installer.exe"
    displayName: 'Sign'
    env:
      PFX_PASSWORD: $(pfxPassword)
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/divvun-installer.exe'
      artifactName: windows
    displayName: 'Publish artifact'
  - powershell: |
      $Env:PATH += ";$(System.DefaultWorkingDirectory)"
      . .\divvun-ci-config\repo\scripts\PahkatDeploySvn.ps1
      .\Pahkat\bin\x86\Release\DivvunInstaller.exe -semver .\app-semver | Out-Null
      $version = Get-Content .\app-semver
      PahkatDeploySvn -SvnUrl https://pahkat.uit.no/repo/divvun-installer -Artifact "$(System.DefaultWorkingDirectory)\divvun-installer.exe" -Package divvun-installer-windows -Version $version
    displayName: 'Deploy to nightly channel'
    env:
      DEPLOY_SVN_USER: $(svnUser)
      DEPLOY_SVN_PASSWORD: $(svnPassword)
      DEPLOY_SVN_COMMIT: $(svnCommit)
